runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb+srv://ssamkyu:wFkIIvQkS9OVrjwn@cluster0.urngty5.mongodb.net/?retryWrites=true&w=majority
  APP_ID: styleshare
  MASTER_KEY: wFkIIvQkS9OVrjwn
  SERVER_URL: https://style-network.herokuapp.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
